kind: Build
apiVersion: builds.katanomi.dev/v1alpha1
spec:
  workspaces:
    - name: source
    - description: golang cache
      name: cache
      optional: true
  tasks:
    - name: trivy-repo-scan
      timeout: 30m
      retries: 0
      taskRef:
        resolver: katanomi.hub
        params:
          - name: kind
            value: task
          - name: name
            value: go-build
      workspaces:
      - name: source
        workspace: source
      - name: cache
        workspace: cache
      when:
      - input: $(build.git.revision.type)
        operator: in
        values:
        - "PullRequest"
      params:
      - name: command
        value: |
          export GOPROXY=https://build-nexus.alauda.cn/repository/golang/,direct
          export GOMAXPROCS=4
          if [ "$GOCACHE" != "" ]; then
            export TOOLBIN=$GOCACHE/../toolbin
            mkdir -p $TOOLBIN
            ls -la $TOOLBIN
          fi

          mkdir -p bin
          export TRIVY_CACHE=$GOCACHE/trivydb
          export TRIVY_DB_REPO=build-harbor.alauda.cn/ops/aquasecurity/trivy-db
          export TRIVY_REPORT_OUTPUT=bin/trivy-report.json
          export TRIVY_SEVERITY=UNKNOWN,MEDIUM,HIGH,CRITICAL
          make trivy-repo-scan
          # TODO: Add report back to PR
      - name: build-outputs-path
        value:
        - "./bin/trivy-report.json"
      - name: tool-image
        value: registry.alauda.cn:60080/devops/builder-go-121:latest

    ### security scan
    - name: govulncheck
      timeout: 30m
      retries: 0
      taskRef:
        resolver: katanomi.hub
        params:
          - name: kind
            value: task
          - name: name
            value: go-build
      workspaces:
      - name: source
        workspace: source
      - name: cache
        workspace: cache
      when:
      - input: $(build.git.revision.type)
        operator: in
        values:
        - "PullRequest"
      params:
      - name: command
        value: |
          export GOPROXY=https://build-nexus.alauda.cn/repository/golang/,direct
          export GOMAXPROCS=8
          if [ "$GOCACHE" != "" ]; then
            export TOOLBIN=$GOCACHE/../toolbin
            mkdir -p $TOOLBIN
            ls -la $TOOLBIN
          fi

          mkdir -p bin
          export VULNCHECK_OUTPUT=bin/vulncheck.txt
          # do not throw an error here immediately, but check whether it should fail in the subsequent logic
          make vulncheck || true
          # count means the line number which contains 'Fixed in' and has fix version
          count=$(grep 'Fixed in' "$VULNCHECK_OUTPUT" | grep -v 'Fixed in: N/A' | wc -l)
          if [ "$count" -gt 0 ]; then
          echo "==> ❌ there are $count vulnerability need to be fixed"
          exit 1
          else
          echo "==> ✅ there is no vulnerability need to be fixed"
          fi
          # TODO: Add report back to PR
      - name: build-outputs-path
        value:
        - "./bin/vulncheck.txt"
      - name: tool-image
        value: registry.alauda.cn:60080/devops/builder-go-121:latest

    ## read oss version
    - name: oss-version
      taskRef:
        kind: ClusterTask
        name: alauda-read-oss-version
      params:
      - name: version-file-path
        value: ".build/opensource-version"
      workspaces:
      - name: source
        workspace: source
    ## ko publish tekton-operator image
    - name: build-operator
      taskRef:
        kind: ClusterTask
        name: alauda-ko-build
      workspaces:
        - name: source
          workspace: source
        - name: cache
          workspace: cache
      params:
        - name: verbose
          value: "false"
        - name: import-path
          value: "./cmd/kubernetes/operator"
        - name: container-image
          value: "build-harbor.alauda.cn/devops/tektoncd/operator/cmd/kubernetes/operator"
        - name: container-image-tag
          value: v$(tasks.oss-version.results.oss-version)-$(tasks.oss-version.results.commit-short-id)
        - name: tool-image
          value: registry.alauda.cn:60080/devops/builder-go-121:latest
    ## ko publish tekton-proxy-webhook image
    - name: build-proxy-webhook
      taskRef:
        kind: ClusterTask
        name: alauda-ko-build
      workspaces:
        - name: source
          workspace: source
        - name: cache
          workspace: cache
      params:
        - name: verbose
          value: "false"
        - name: import-path
          value: "./cmd/kubernetes/proxy-webhook"
        - name: container-image
          value: "build-harbor.alauda.cn/devops/tektoncd/operator/cmd/kubernetes/proxy-webhook"
        - name: container-image-tag
          value: v$(tasks.oss-version.results.oss-version)-$(tasks.oss-version.results.commit-short-id)
        - name: tool-image
          value: registry.alauda.cn:60080/devops/builder-go-121:latest
    ## ko publish tekton-webhook image
    - name: build-webhook
      taskRef:
        kind: ClusterTask
        name: alauda-ko-build
      workspaces:
        - name: source
          workspace: source
        - name: cache
          workspace: cache
      params:
        - name: verbose
          value: "false"
        - name: import-path
          value: "./cmd/kubernetes/webhook"
        - name: container-image
          value: "build-harbor.alauda.cn/devops/tektoncd/operator/cmd/kubernetes/webhook"
        - name: container-image-tag
          value: v$(tasks.oss-version.results.oss-version)-$(tasks.oss-version.results.commit-short-id)
        - name: tool-image
          value: registry.alauda.cn:60080/devops/builder-go-121:latest
    #################
    # golang-test
    #################
    - name: golang-test
      taskRef:
        kind: ClusterTask
        name: go-unit-test
      params:
        - name: command
          value: |
            export GOPROXY=https://build-nexus.alauda.cn/repository/golang/,https://goproxy.cn,direct
            export CGO_ENABLED=0
            export GONOSUMDB=*
            export GOMAXPROCS=8

            echo "`date` downloading dependencies"
            go mod download

            echo "`date` running tests"
            go test -v -json -coverpkg=./... -coverprofile ./cover.out ./... | tee ./test.json

            echo "`date` done"

        - name: quality-gate-rules
          value:
            - lines-coverage=10
            - passed-tests-rate=100
        - name: tool-image
          value: registry.alauda.cn:60080/devops/builder-go-121:latest
        - name: test-report-path
          value: ./test.json
        - name: coverage-report-path
          value: ./cover.out
      workspaces:
        - name: source
          workspace: source
        - name: cache
          workspace: cache
    #################
    # code-scan
    #################
    - name: code-scan
      timeout: 30m
      retries: 0
      runAfter:
        - golang-test
      taskRef:
        kind: ClusterTask
        name: sonarqube-analysis
      workspaces:
        - name: source
          workspace: source
      params:
        - name: server
          value: https://build-sonar.alauda.cn

    - name: trivy-scan
      when:
        - input: $(build.git.revision.type)
          operator: in
          values:
          - "PullRequest"
      timeout: 30m
      retries: 1
      taskRef:
        resolver: katanomi.hub
        params:
          - name: kind
            value: task
          - name: name
            value: trivy-image-scan
      workspaces:
        - name: source
          workspace: source
        - name: cache
          workspace: cache
      params:
        - name: targets
          value:
            - $(tasks.build-webhook.results.ociContainerImageBuild-url)
            - $(tasks.build-operator.results.ociContainerImageBuild-url)
            - $(tasks.build-proxy-webhook.results.ociContainerImageBuild-url)
        - name: quality-gate-rules
          value:
            - severity=Medium
        - name: scan-flags
          value:
            - db.skip-update=false
            - db.repository=build-harbor.alauda.cn/ops/aquasecurity/trivy-db

  #################
  # runTemplate
  #################
  runTemplate:
    spec:
      # set this information in the configuration `build-manager-config`
      workspaces:
        - name: cache
          persistentVolumeClaim:
            claimName: build-cache
          subPath: golang

      taskRunSpecs:
        - pipelineTaskName: trivy-repo-scan
          stepOverrides:
          - name: go-build
            resources:
              requests:
                cpu: "1"
                memory: 1Gi
              limits:
                cpu: "1"
                memory: 1Gi
        - pipelineTaskName: govulncheck
          stepOverrides:
          - name: go-build
            resources:
              requests:
                cpu: "8"
                memory: 10Gi
              limits:
                cpu: "8"
                memory: 10Gi
        - pipelineTaskName: golang-test
          stepOverrides:
            - name: prepare
              resources:
                limits:
                  cpu: 100m
                  memory: 100Mi
                requests:
                  cpu: 50m
                  memory: 50Mi
            - name: test
              resources:
                requests:
                  cpu: "6"
                  memory: 4Gi
                limits:
                  cpu: "8"
                  memory: 6Gi
            - name: analysis
              resources:
                limits:
                  cpu: 100m
                  memory: 100Mi
                requests:
                  cpu: 50m
                  memory: 50Mi
